version: "0.2"
ignorePaths: [
  ".github/**/*"
]
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
    scope: "folder"
dictionaries:
  - custom-dictionary
words: []
ignoreWords: []
import: []
