use std::hash::Hash;
use std::hash::Hasher;

use prismal_window::prelude::winit;
pub use winit::event::VirtualKeyCode as WinitKeyCode;

use serde::{Deserialize, Serialize};

/// Symbolic name for a keyboard key.
#[derive(Debug, Ord, PartialOrd, Eq, Clone, Copy)]
#[derive(Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
#[repr(u16)]
pub enum KeyCode {
    /// The '1' key over the letters.
    Key1,
    /// The '2' key over the letters.
    Key2,
    /// The '3' key over the letters.
    Key3,
    /// The '4' key over the letters.
    Key4,
    /// The '5' key over the letters.
    Key5,
    /// The '6' key over the letters.
    Key6,
    /// The '7' key over the letters.
    Key7,
    /// The '8' key over the letters.
    Key8,
    /// The '9' key over the letters.
    Key9,
    /// The '0' key over the 'O' and 'P' keys.
    Key0,

    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    /// The Escape key, next to F1.
    Escape,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,

    /// Print Screen/SysRq.
    Snapshot,
    /// Scroll Lock.
    ScrollLock,
    /// Pause/Break key, next to Scroll lock.
    Pause,

    /// `Insert`, next to Backspace.
    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,

    Left,
    Up,
    Right,
    Down,

    /// The Backspace key, right over Enter.
    Backspace,
    /// The Enter key.
    Return,
    /// The space bar.
    Space,

    /// The "Compose" key on Linux.
    Compose,

    Caret,

    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadDivide,
    NumpadDecimal,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    NumpadMultiply,
    NumpadSubtract,

    AbntC1,
    AbntC2,
    Apostrophe,
    Apps,
    Asterisk,
    At,
    Ax,
    Backslash,
    Calculator,
    Capital,
    Colon,
    Comma,
    Convert,
    Equals,
    Grave,
    Kana,
    Kanji,
    LAlt,
    LBracket,
    LControl,
    LShift,
    LWin,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    Mute,
    MyComputer,
    // also called "Next"
    NavigateForward,
    // also called "Prior"
    NavigateBackward,
    NextTrack,
    NoConvert,
    OEM102,
    Period,
    PlayPause,
    Plus,
    Power,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    RShift,
    RWin,
    Semicolon,
    Slash,
    Sleep,
    Stop,
    Sysrq,
    Tab,
    Underline,
    Unlabeled,
    VolumeDown,
    VolumeUp,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Yen,
    Copy,
    Paste,
    Cut,
}

impl PartialEq for KeyCode {
    fn eq(&self, other: &Self) -> bool {
        core::mem::discriminant(self) == core::mem::discriminant(other)
    }
}

impl Hash for KeyCode {
    fn hash<H: Hasher>(&self, state: &mut H) {
        state.write_u16((*self) as u16)
    }
}

impl From<WinitKeyCode> for KeyCode {
    fn from(src: WinitKeyCode) -> Self {
        match src {
            WinitKeyCode::Key1 => Self::Key1,
            WinitKeyCode::Key2 => Self::Key2,
            WinitKeyCode::Key3 => Self::Key3,
            WinitKeyCode::Key4 => Self::Key4,
            WinitKeyCode::Key5 => Self::Key5,
            WinitKeyCode::Key6 => Self::Key6,
            WinitKeyCode::Key7 => Self::Key7,
            WinitKeyCode::Key8 => Self::Key8,
            WinitKeyCode::Key9 => Self::Key9,
            WinitKeyCode::Key0 => Self::Key0,
            WinitKeyCode::A => Self::A,
            WinitKeyCode::B => Self::B,
            WinitKeyCode::C => Self::C,
            WinitKeyCode::D => Self::D,
            WinitKeyCode::E => Self::E,
            WinitKeyCode::F => Self::F,
            WinitKeyCode::G => Self::G,
            WinitKeyCode::H => Self::H,
            WinitKeyCode::I => Self::I,
            WinitKeyCode::J => Self::J,
            WinitKeyCode::K => Self::K,
            WinitKeyCode::L => Self::L,
            WinitKeyCode::M => Self::M,
            WinitKeyCode::N => Self::N,
            WinitKeyCode::O => Self::O,
            WinitKeyCode::P => Self::P,
            WinitKeyCode::Q => Self::Q,
            WinitKeyCode::R => Self::R,
            WinitKeyCode::S => Self::S,
            WinitKeyCode::T => Self::T,
            WinitKeyCode::U => Self::U,
            WinitKeyCode::V => Self::V,
            WinitKeyCode::W => Self::W,
            WinitKeyCode::X => Self::X,
            WinitKeyCode::Y => Self::Y,
            WinitKeyCode::Z => Self::Z,
            WinitKeyCode::Escape => Self::Escape,
            WinitKeyCode::F1 => Self::F1,
            WinitKeyCode::F2 => Self::F2,
            WinitKeyCode::F3 => Self::F3,
            WinitKeyCode::F4 => Self::F4,
            WinitKeyCode::F5 => Self::F5,
            WinitKeyCode::F6 => Self::F6,
            WinitKeyCode::F7 => Self::F7,
            WinitKeyCode::F8 => Self::F8,
            WinitKeyCode::F9 => Self::F9,
            WinitKeyCode::F10 => Self::F10,
            WinitKeyCode::F11 => Self::F11,
            WinitKeyCode::F12 => Self::F12,
            WinitKeyCode::F13 => Self::F13,
            WinitKeyCode::F14 => Self::F14,
            WinitKeyCode::F15 => Self::F15,
            WinitKeyCode::F16 => Self::F16,
            WinitKeyCode::F17 => Self::F17,
            WinitKeyCode::F18 => Self::F18,
            WinitKeyCode::F19 => Self::F19,
            WinitKeyCode::F20 => Self::F20,
            WinitKeyCode::F21 => Self::F21,
            WinitKeyCode::F22 => Self::F22,
            WinitKeyCode::F23 => Self::F23,
            WinitKeyCode::F24 => Self::F24,
            WinitKeyCode::Snapshot => Self::Snapshot,
            WinitKeyCode::Scroll => Self::ScrollLock,
            WinitKeyCode::Pause => Self::Pause,
            WinitKeyCode::Insert => Self::Insert,
            WinitKeyCode::Home => Self::Home,
            WinitKeyCode::Delete => Self::Delete,
            WinitKeyCode::End => Self::End,
            WinitKeyCode::PageDown => Self::PageDown,
            WinitKeyCode::PageUp => Self::PageUp,
            WinitKeyCode::Left => Self::Left,
            WinitKeyCode::Up => Self::Up,
            WinitKeyCode::Right => Self::Right,
            WinitKeyCode::Down => Self::Down,
            WinitKeyCode::Back => Self::Backspace,
            WinitKeyCode::Return => Self::Return,
            WinitKeyCode::Space => Self::Space,
            WinitKeyCode::Compose => Self::Compose,
            WinitKeyCode::Caret => Self::Caret,
            WinitKeyCode::Numlock => Self::Numlock,
            WinitKeyCode::Numpad0 => Self::Numpad0,
            WinitKeyCode::Numpad1 => Self::Numpad1,
            WinitKeyCode::Numpad2 => Self::Numpad2,
            WinitKeyCode::Numpad3 => Self::Numpad3,
            WinitKeyCode::Numpad4 => Self::Numpad4,
            WinitKeyCode::Numpad5 => Self::Numpad5,
            WinitKeyCode::Numpad6 => Self::Numpad6,
            WinitKeyCode::Numpad7 => Self::Numpad7,
            WinitKeyCode::Numpad8 => Self::Numpad8,
            WinitKeyCode::Numpad9 => Self::Numpad9,
            WinitKeyCode::NumpadAdd => Self::NumpadAdd,
            WinitKeyCode::NumpadDivide => Self::NumpadDivide,
            WinitKeyCode::NumpadDecimal => Self::NumpadDecimal,
            WinitKeyCode::NumpadComma => Self::NumpadComma,
            WinitKeyCode::NumpadEnter => Self::NumpadEnter,
            WinitKeyCode::NumpadEquals => Self::NumpadEquals,
            WinitKeyCode::NumpadMultiply => Self::NumpadMultiply,
            WinitKeyCode::NumpadSubtract => Self::NumpadSubtract,
            WinitKeyCode::AbntC1 => Self::AbntC1,
            WinitKeyCode::AbntC2 => Self::AbntC2,
            WinitKeyCode::Apostrophe => Self::Apostrophe,
            WinitKeyCode::Apps => Self::Apps,
            WinitKeyCode::Asterisk => Self::Asterisk,
            WinitKeyCode::At => Self::At,
            WinitKeyCode::Ax => Self::Ax,
            WinitKeyCode::Backslash => Self::Backslash,
            WinitKeyCode::Calculator => Self::Calculator,
            WinitKeyCode::Capital => Self::Capital,
            WinitKeyCode::Colon => Self::Colon,
            WinitKeyCode::Comma => Self::Comma,
            WinitKeyCode::Convert => Self::Convert,
            WinitKeyCode::Equals => Self::Equals,
            WinitKeyCode::Grave => Self::Grave,
            WinitKeyCode::Kana => Self::Kana,
            WinitKeyCode::Kanji => Self::Kanji,
            WinitKeyCode::LAlt => Self::LAlt,
            WinitKeyCode::LBracket => Self::LBracket,
            WinitKeyCode::LControl => Self::LControl,
            WinitKeyCode::LShift => Self::LShift,
            WinitKeyCode::LWin => Self::LWin,
            WinitKeyCode::Mail => Self::Mail,
            WinitKeyCode::MediaSelect => Self::MediaSelect,
            WinitKeyCode::MediaStop => Self::MediaStop,
            WinitKeyCode::Minus => Self::Minus,
            WinitKeyCode::Mute => Self::Mute,
            WinitKeyCode::MyComputer => Self::MyComputer,
            WinitKeyCode::NavigateForward => Self::NavigateForward,
            WinitKeyCode::NavigateBackward => Self::NavigateBackward,
            WinitKeyCode::NextTrack => Self::NextTrack,
            WinitKeyCode::NoConvert => Self::NoConvert,
            WinitKeyCode::OEM102 => Self::OEM102,
            WinitKeyCode::Period => Self::Period,
            WinitKeyCode::PlayPause => Self::PlayPause,
            WinitKeyCode::Plus => Self::Plus,
            WinitKeyCode::Power => Self::Power,
            WinitKeyCode::PrevTrack => Self::PrevTrack,
            WinitKeyCode::RAlt => Self::RAlt,
            WinitKeyCode::RBracket => Self::RBracket,
            WinitKeyCode::RControl => Self::RControl,
            WinitKeyCode::RShift => Self::RShift,
            WinitKeyCode::RWin => Self::RWin,
            WinitKeyCode::Semicolon => Self::Semicolon,
            WinitKeyCode::Slash => Self::Slash,
            WinitKeyCode::Sleep => Self::Sleep,
            WinitKeyCode::Stop => Self::Stop,
            WinitKeyCode::Sysrq => Self::Sysrq,
            WinitKeyCode::Tab => Self::Tab,
            WinitKeyCode::Underline => Self::Underline,
            WinitKeyCode::Unlabeled => Self::Unlabeled,
            WinitKeyCode::VolumeDown => Self::VolumeDown,
            WinitKeyCode::VolumeUp => Self::VolumeUp,
            WinitKeyCode::Wake => Self::Wake,
            WinitKeyCode::WebBack => Self::WebBack,
            WinitKeyCode::WebFavorites => Self::WebFavorites,
            WinitKeyCode::WebForward => Self::WebForward,
            WinitKeyCode::WebHome => Self::WebHome,
            WinitKeyCode::WebRefresh => Self::WebRefresh,
            WinitKeyCode::WebSearch => Self::WebSearch,
            WinitKeyCode::WebStop => Self::WebStop,
            WinitKeyCode::Yen => Self::Yen,
            WinitKeyCode::Copy => Self::Copy,
            WinitKeyCode::Paste => Self::Paste,
            WinitKeyCode::Cut => Self::Cut,
        }
    }
}
